FROM node:lts-alpine

# The /app directory should act as the main application directory
WORKDIR /app/client

COPY package*.json ./

RUN npm install
# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . .

EXPOSE 8080

CMD [ "npm", "run", "serve" ]
