FROM node:lts-alpine

RUN npm install -g http-server
# The /app directory should act as the main application directory
WORKDIR /usr/src/app/client

COPY package*.json ./

RUN npm install 
# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY . .

RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist" ]
