version: "3"
services:
  nodejs-backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"
    container_name: shui-backend
    env_file: 
      - ./api/.env
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  vuejs-client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    container_name: shui-frontend
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
