
services:
  nodejs-backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: suhi-backend
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  vuejs-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: suhi-frontend
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
